---
name: "Wortell Cloud AzOps - Init"

# 
# Parameters
# Required parameters to install AzOps in the correct way.
# Required parameters are:
# - sc: Name of the service connection
# 
# Optional parameters are:
# - pull: Default naming is Wortell Cloud AzOps - Pull, enter a diff value if required.
# - push: Default naming is Wortell Cloud AzOps - Push, enter a diff value if required.
# - validate: Default naming is Wortell Cloud AzOps - Validate, enter a diff value if required.
# - update: Default naming is Wortell Cloud AzOps - Update, enter a diff value if required.
#

parameters:
- name: sc
  displayName: Service Connection used for AzOps
  type: string
- name: armclientid
  displayName: Azure AD App Registration Client ID used for AzOps
  type: string
- name: armclientsecret
  displayName: Azure AD App Registration Client Secret used for AzOps
  type: string
- name: armsubscriptionid
  displayName: Azure Management Subscription ID used for AzOps
  type: string
- name: armtenantid
  displayName: Azure Tenant ID used for AzOps
  type: string
- name: vars
  displayName: Variable Group in Library used for AzOps custom naming convention
  default: wortell-cloud-azops-credentials
  type: string
- name: keyvault
  displayName: An option to check if we are going to use the KeyVault instead of the Library Variable Group
  default: false
  type: string
- name: pull
  displayName: Pull pipeline custom naming convention
  default: false
  type: string
- name: push
  displayName: Push pipeline custom naming convention
  default: false
  type: string
- name: validate
  displayName: Validate pipeline custom naming convention
  default: false
  type: string
- name: update
  displayName: Update pipeline custom naming convention
  default: false
  type: string

# 
# Triggers
# Automated triggers are configured via Branch Policies
# within Azure Repos. It's also recommended to manually
# disable CI triggers with overrides.
#

trigger: none

#
# Pipelines
# Triggers this pipeline upon the completion of
# the Push pipeline.
#

resources:
  pipelines:
    - pipeline: 'Init'
      source: 'Wortell Cloud AzOps - Pull'
      trigger:
        branches:
          include:
            - main

variables:
  
  #
  # Shared variables
  # Include shared variables from the 'vars.yml' file
  # to not have to repeat them in every pipeline.
  #

  - template: .templates/vars.yml

  #
  # Folder Name
  # By default we generate the hierachy within the
  # 'azops' folder within the root of the repository.
  # If this property is modified, the config value within
  # the settings.json file - Core.State will also need
  # to be changed.
  #
  # Default: root
  #

  - name: folder
    value: "root"

  #
  # Branch Name
  # As part of the Pull workflow we check a temporary branch
  # this branch was previously know as system, this value can
  # be changed if this name is already reserved for other systems
  # within the repository.
  #
  # Default: automated
  #

  - name: branch
    value: "automated"

  #
  # Commit Message
  # During the Pull workflow, the changes are commited to the
  # temporary branch, the message which is applied within the
  # Git history can be changed as needed.
  #
  # Default: Automated commit
  #

  - name: commit_message
    value: "Automated commit"

  #
  # Pull Request
  # The generated Pull Request for the Pull workflow can be
  # modified to help indicate when changes we're merged in the
  # Git history.
  #
  # Default: Automated state
  #

  - name: pull_request
    value: "Automated State"

jobs:

  - job: pull

    #
    # Pull
    #

    displayName: "Pull"
    pool:
      vmImage: "ubuntu-20.04"

    steps:

      #
      # Shared steps
      # Include shared steps from the 'shared.yml' file
      # to not have to repeat them in every pipeline.
      #
      
      - template: .templates/sharedSteps.yml

      #
      # Configure
      # Set global options
      #

      - task: Bash@3
        displayName: "Configure"
        inputs:
          targetType: "inline"
          script: |
            git config user.name "Azure DevOps"
            git config user.email "azuredevops@microsoft.com"

      #
      # Checkout
      # Switch branches
      #

      - task: Bash@3
        displayName: "Checkout"
        inputs:
          targetType: "inline"
          script: |
            git checkout -b $(branch)

      #
      # Initialize
      # Generate new state data
      #

      - task: PowerShell@2
        displayName: "Initialize"
        inputs:
          targetType: "inline"
          script: |
            $Env:PSModulePath = $Env:PSModulePath, '$(modulesFolder)' -join [IO.Path]::PathSeparator
            Import-PSFConfig -Path settings.json -Schema MetaJson -EnableException
            Invoke-AzOpsPull -Rebuild
            Get-Job | Remove-Job -Force

      #
      # Status
      # Check for data changes
      #

      - task: Bash@3
        displayName: "Status"
        inputs:
          targetType: "inline"
          script: |
            STATUS=$(git status --short $(folder))
            echo $STATUS
            if [ -z "$STATUS" ]
            then
              echo "##vso[task.setvariable variable=state]stop"
            else
              echo "##vso[task.setvariable variable=state]continue"
            fi

      #
      # Add
      # Add file content to index
      #

      - task: Bash@3
        displayName: "Add"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            git add ./$(folder)


      #
      # Commit
      # Record changes to the repository
      #

      - task: Bash@3
        displayName: "Commit"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            git commit -m "$(commit_message)"


      #
      # Push
      # Update remote refs along with associated objects
      #

      - task: Bash@3
        displayName: "Push"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            git push origin $(branch) -f


      #
      # Merge
      # Update remote refs along with associated objects
      #

      - task: Bash@3
        displayName: "Merge"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            # Open new PR
            PROut=$(
              az repos pr create \
              --title "$(pull_request)" \
              --source-branch "$(branch)" \
              --target-branch "main" \
              --squash true \
              --delete-source-branch true \
              --auto-complete true \
            );

            # Get PR ID and check status
            PRid=$(echo $PROut | jq -r '.pullRequestId');
            PRStatus=$(az repos pr show --id $PRid | jq .status);

            # If PR is not completed, then complete it bypassing policy
            if [ $PRStatus == "\"active\"" ]; then
              echo "Completing PR bypassing branch policy"
              az repos pr update --status completed --id $PRid --bypass-policy true --bypass-policy-reason "Automated pull request" > /dev/null 2>&1
            fi;
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
