---
name: "Wortell Cloud AzOps - Update"

# BEST IN THE WORLD
# Triggers
# Automated triggers are disabled for the Update pipelines
# This pipeline should be run on a manual basis to avoid
# any possible conflicts. It's also recommended to manually
# disable CI triggers with overrides.
#

trigger: none

variables:

  #
  # Branch Name
  #
  # Default: update
  #

  branch: 'update'

  #
  # Commit Name
  #
  # Default: Update commit
  #

  commit: 'Update commit'

jobs:

  - job: update

    #
    # Update
    #

    displayName: "Update"
    pool:
      vmImage: "ubuntu-20.04"

    steps:

      #
      # Checkout
      # Checks-out the repository
      # Repo: origin
      #

      - checkout: self
        fetchDepth: 0
        persistCredentials: true
        path: "origin"

      #
      # Configure
      # Set global options
      #

      - task: Bash@3
        displayName: "Configure"
        inputs:
          targetType: "inline"
          workingDirectory: "../origin"
          script: |
            git config user.name "Wortell Cloud AzOps"
            git config user.email "wortellcloudazops@wortell.nl"

      #
      # Checkout
      # Checks-out the repository
      # Repo: upstream
      #

      - task: PowerShell@2
        displayName: Checkout Repo
        inputs:
          targetType: 'inline'
          script: |
            Remove-Item upstream -Recurse -Force -ErrorAction Ignore
            git clone https://github.com/wortell/cloud-azops upstream
            cd upstream
            git checkout main
          workingDirectory: '$(Pipeline.Workspace)' 

      #
      # Copy
      # Update the workflow files
      #

      - task: Bash@3
        displayName: "Copy"
        inputs:
          targetType: "inline"
          workingDirectory: ".."
          script: |
            test -f ./origin/.pipelines/patch.yml && rm -f ./origin/.pipelines/patch.yml
            cp -R -v ./upstream/.pipelines/ ./origin/

      #
      # Commit
      # Record changes to the repository
      #

      - task: Bash@3
        displayName: "Commit"
        inputs:
          targetType: "inline"
          workingDirectory: "../origin"
          script: |
            DIFF=$(git diff --name-only)
            echo $DIFF
            if [ -n "$DIFF" ]
            then
              git checkout -b "$(branch)"
              git add .pipelines/
              git commit -m "$(commit)"
              git push origin "$(branch)" -f
              echo "##vso[task.setvariable variable=state]continue"
            fi

      #
      # Create
      # Open new Pull Request for proposed changes
      #

      - task: Bash@3
        displayName: "Create"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          workingDirectory: "../origin"
          script: |
            az repos pr create \
              --auto-complete $true \
              --title "Wortell Cloud AzOps Update Version" \
              --description "New version available from the upstream repository." \
              --source-branch "$(branch)" \
              --target-branch "main"
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
